dataset:
  # repo_id: lerobot/aloha_sim_transfer_cube_human
  # repo_id: lerobot/pusht
  repo_id: HuggingFaceVLA/libero
  # repo_id: lerobot/metaworld_mt50



policy:
  type: pi05
  # chunk_size: 10
  # n_action_steps: 10

  device: npu
  push_to_hub: false
  dtype: bfloat16
  gradient_checkpointing: true
  pretrained_path: lerobot/pi05_base
  compile_model: true
  normalization_mapping: {"ACTION": "MEAN_STD", "STATE": "MEAN_STD", "VISUAL": "IDENTITY"}

# output_dir: ./ckpt/pi05_meta
output_dir: ./ckpt/pi05_libero
batch_size: 64
# job_name: pi05_meta
job_name: pi05_libero
steps: 20000
eval_freq: -1  # No evaluation during distributed training
save_checkpoint: true
save_freq: 5_000
use_policy_training_preset: true

wandb:
  enable: true

  # project: pi05_meta
  project: pi05_libero
  entity: jeffreytseng123-chinese-academy-of-sciences
  disable_artifact: true