dataset:
  # repo_id: lerobot/metaworld_mt50
  repo_id: HuggingFaceVLA/libero


policy:
  type: smolvla

  device: npu
  push_to_hub: false

# env:
#   type: metaworld 
#   task: assembly-v3,dial-turn-v3,handle-press-side-v3

# eval:
#   batch_size: 1
#   n_episodes: 1

save_checkpoint: true
output_dir: ./ckpt/smovla_meta
batch_size: 32
job_name: smovla_meta
steps: 10000
eval_freq: -1
save_checkpoint: true
save_freq: 5_000
use_policy_training_preset: true

wandb:
  enable: true

  project: smolvla_meta
  entity: jeffreytseng123-chinese-academy-of-sciences
  disable_artifact: true

# dataset:
#   repo_id: lerobot/pusht 


# policy:
#   type: smolvla

#   device: npu
#   push_to_hub: false

# # env:
# #   type: metaworld 
# #   task: assembly-v3,dial-turn-v3,handle-press-side-v3

# # eval:
# #   batch_size: 1
# #   n_episodes: 1

# save_checkpoint: true
# output_dir: ./ckpt/smovla_pusht
# batch_size: 32
# job_name: smovla_pusht
# steps: 10000
# eval_freq: 1000
# save_checkpoint: true
# save_freq: 5_000
# use_policy_training_preset: true

# wandb:
#   enable: true

#   project: smolvla_pusht
#   entity: jeffreytseng123-chinese-academy-of-sciences
#   disable_artifact: true